export enum PermissionType {
  COMPANY_ADMIN = "COMPANY_ADMIN",
  COMPANY_EDITOR = "COMPANY_EDITOR",
  COMPANY_EMPLOYEE = "COMPANY_EMPLOYEE",
  PROJECT_ADMIN = "PROJECT_ADMIN",
  PROJECT_EDITOR = "PROJECT_EDITOR",
  PROJECT_ASSIGNED_EMPLOYEE = "PROJECT_ASSIGNED_EMPLOYEE",
  TASK_ASSIGNED_EMPLOYEE = "TASK_ASSIGNED_EMPLOYEE"
}
