server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:56321/trainingportaldb
    username: devuser
    password: devpassword
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: ${BACKEND_SMTP_HOST}
    port: ${BACKEND_SMTP_PORT}
    username: ${BACKEND_SMTP_USERNAME}
    password: ${BACKEND_SMTP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactory:
            port: ${BACKEND_SMTP_PORT}
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
            trust: ${BACKEND_SMTP_HOST}
          auth: true

logging:
  level:
    root: info
    org.springframework: info